name: Daily News Topic Update

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allow manual triggering

# Add this permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-topics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download it_core_news_sm
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removed cache setting to avoid the error
      
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Run news scraper
        run: |
          python -c "from scraper.scraper import run_scraper; run_scraper()"
      
      - name: Run topic analyzer
        run: |
          python -c "from analysis.topic_analyzer import run_analyzer; run_analyzer()"
      
      - name: Build site
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4