name: Daily News Topic Update

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust as needed)
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-topics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download it_core_news_sm
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Run news scraper
        run: |
          python -c "from scraper.scraper import run_scraper; run_scraper()"
      
      - name: Run topic analyzer
        run: |
          python -c "from analysis.topic_analyzer import run_analyzer; run_analyzer()"
      
      - name: Build site
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update topics for ${{ github.event.repository.updated_at }}'